#!/usr/bin/env python3
"""Generate the "dtbo overlay sink" dtsi for Motorola nairo.

nairo's ABL picks an overlay from the dtbo partition and refuses to boot if it
cannot apply it, and it rejects modified dtbo images. So the mainline DTB must
accept the stock overlays: every label they reference (their __fixups__) gets a
/__symbols__ entry pointing at an empty node under a disabled
/nairo-dtbo-sink. The downstream content lands there and is ignored; our own
labels are deliberately not exported, so the overlays cannot touch real nodes.

usage: gen_dtbo_sink.py dtbo.img out.dtsi
"""
import struct
import subprocess
import sys
import tempfile

PHANDLE_BASE = 0x7f000000

def entries(path):
    d = open(path, 'rb').read()
    magic, _, _, esz, cnt, eoff, _, _ = struct.unpack('>8I', d[:32])
    assert magic == 0xd7b7ab1e, 'not a DTBO table image'
    for k in range(cnt):
        size, off = struct.unpack('>2I', d[eoff + k * esz:eoff + k * esz + 8])
        yield d[off:off + size]

def fixup_labels(blob):
    with tempfile.NamedTemporaryFile(suffix='.dtbo') as f:
        f.write(blob)
        f.flush()
        out = subprocess.run(['fdtget', '-p', f.name, '/__fixups__'],
                             capture_output=True, text=True, check=True).stdout
    return out.split()

def main():
    src, dst = sys.argv[1], sys.argv[2]
    labels = sorted({l for e in entries(src) for l in fixup_labels(e)})
    o = ['// SPDX-License-Identifier: BSD-3-Clause',
         '/*',
         ' * Generated by tools/gen_dtbo_sink.py from the stock dtbo image - do not edit.',
         ' *',
         ' * nairo ABL applies a stock dtbo overlay and aborts the boot if that fails.',
         ' * Resolve every label those overlays reference to an inert node, so they',
         ' * apply without touching the real hardware description.',
         ' */',
         '',
         '/ {',
         '\tnairo-dtbo-sink {',
         '\t\tstatus = "disabled";']
    for i, l in enumerate(labels):
        o += ['', f'\t\t{l} {{', f'\t\t\tphandle = <{PHANDLE_BASE + i:#x}>;', '\t\t};']
    o += ['\t};', '', '\t__symbols__ {']
    o += [f'\t\t{l} = "/nairo-dtbo-sink/{l}";' for l in labels]
    o += ['\t};', '};', '']
    open(dst, 'w').write('\n'.join(o))
    print(f'{len(labels)} labels from {src}')

if __name__ == '__main__':
    main()
